//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agency
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public double Amount { get; set; }
        public double GrandTotal { get; set; }
        public string IsPaid { get; set; }
        public Nullable<int> Store_Id { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual Store Store1 { get; set; }
    }
}
