//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesReport
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> SalesYear { get; set; }
        public Nullable<int> SalesMedicineId { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
